repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.285
    hooks:
    - id: ruff
      name: "[py   -   lint] ruff"
      args:
        [
          "--fix"
        ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
    - id: mypy
      name: "[py   - typing] mypy"
      language: system
      pass_filenames: false
      args:
        [
          app
        ]
